name: Release rbchunk

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    container:
      image: rust:1.68-buster
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Crate Publish
      uses: katyo/publish-crates@v2
      with:
        registry-token: ${{ secrets.CRATE_TOKEN }}
    - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
